apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: uurapport-backend
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - "https://uurapport.ekstern.dev.nav.no"
#    - "https://uurapport.ansatt.dev.nav.no"
  prometheus:
    enabled: true
    path: /open/metrics
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: "uurapport-frontend"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        groups:
          - id: '07bca51b-e5dc-484a-ac09-685e61244b6b' #admins
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /open/*
        - /static/**
        - /api/**
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-custom-1-4096
        diskType: SSD
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: uurapport
        maintenance:
          day: 1
          hour: 4
        cascadingDelete: false
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:
    - name: ENVIRONMENT
      value: "dev-gcp"
    - name: PORT
      value: "8080"
    - name: ADMIN_GROUP
      value: "95fa4c83-0d92-4aa0-83b0-c80487350318"
    - name: CORS_ALLOWED_ORIGIN
      value: "*.ansatt.dev.nav.no,*.ekstern.dev.nav.no"
    - name: DATABASE_URL
      value: "$(NAIS_DATABASE_UURAPPORT_BACKEND_UURAPPORT_JDBC_URL)"